* Packages

** Startup

*** Repositories and initialisation

Enable melpa archive and making sure packages work
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/lisp")
  (require 'package)
  (setq package-enable-at-startup nil)
  (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                           ("melpa" . "http://melpa.org/packages/")))
  (package-initialize)
#+END_SRC

*** Use-package

Install use-package if not installed
#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+END_SRC

** Installed Packages

*** Pinentry

This package lets emacs be used for gpg authentication
#+BEGIN_SRC emacs-lisp
  (use-package pinentry
    :ensure t
    :init
    (setq epg-pinentry-mode 'loopback)
    (pinentry-start))
#+END_SRC

*** Org

**** Github markdown

#+BEGIN_SRC emacs-lisp
  (use-package ox-gfm
    :ensure t)
#+END_SRC

**** Html export

#+BEGIN_SRC emacs-lisp
  (use-package htmlize
    :ensure t)
#+END_SRC

*** EXWM - Emacs X Window Manager

Manipulate X windows as emacs buffers.
#+BEGIN_SRC emacs-lisp
  (use-package exwm
    :ensure t
    :config
    (require 'exwm-config)
    (exwm-config-default)
    (setq exwm-workspace-number 4))
#+END_SRC

*** Desktop-environment (useful with EXWM)

#+BEGIN_SRC emacs-lisp
  (use-package desktop-environment
    :ensure t
    :config (desktop-environment-mode))
#+END_SRC

*** openwith

Open files using external program. I only use it for videos.

#+BEGIN_SRC emacs-lisp
(use-package openwith
  :ensure t
  :config
  (openwith-mode nil)
  (setq openwith-associations
        '(("\\.\\(?:mpe?g\\|avi\\|mp4\\|webm\\|mkv\\|wmv\\)\\'" "mpv"
           (file)))))
#+END_SRC

*** dwm-mode
Manipulate emacs windows similarly to suckless' dwm.

#+BEGIN_SRC emacs-lisp
  (use-package dwm
    :load-path "~/.emacs.d/lisp/"
    :config (setq dwm-mode-emulate-keybindings t))
#+END_SRC

*** Programming
**** Geiser

#+BEGIN_SRC emacs-lisp
  (use-package geiser
    :ensure t)
#+END_SRC

**** SLIME

#+BEGIN_SRC emacs-lisp
  (use-package slime
    :ensure t)
#+END_SRC

*** Completion

**** Company

A very good package for auto-completion
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :init
    (global-company-mode)
    :config
    (setq company-idle-delay 0))
#+END_SRC

*** "Applications"

**** vterm

#+BEGIN_SRC emacs-lisp
  (use-package vterm
    :load-path "~/.emacs.d/emacs-libvterm")
#+END_SRC

**** Mingus

A nice mpd front-end in emacs
(I couldn't get EMMS working with mopidy)
#+BEGIN_SRC emacs-lisp
  (use-package mingus
    :ensure t)
#+END_SRC

**** Notmuch

A simple email client, with emphasis on searching
#+BEGIN_SRC emacs-lisp
  (use-package notmuch
    :ensure t
    :config
    (setq notmuch-archive-tags '("-unread" "-inbox")
          notmuch-search-oldest-first nil))
#+END_SRC

**** Transmission

An emacs front-end for the transmission bittorrent daemon
#+BEGIN_SRC emacs-lisp
  (use-package transmission
    :ensure t)
#+END_SRC

*** Appearance
**** Theme

***** base16

Base16 is a nice theme framework, but moe-theme is my new best friend.
#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'base16-theme)
    (package-refresh-contents)
    (package-install 'base16-theme))
  (setq base16-distinct-fringe-background nil)
  (setq base16-theme-256-color-source "colors")
                                          ;  (load-theme 'base16-bright t)
#+END_SRC

**** Rainbow-mode

This package highlights hex colours
(also install xterm-color to use in a terminal emulator)
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :config
    (global-set-key (kbd "C-c h") 'rainbow-mode))
#+END_SRC

**** xterm-color

Allows a terminal emulator to use 256 colors
#+BEGIN_SRC emacs-lisp
  (use-package xterm-color
    :ensure t)
#+END_SRC

**** Rainbow-delimiters

Minor mode that highlights parentheses well
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :init
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
#+END_SRC

*** god-mode

#+BEGIN_SRC emacs-lisp
  (use-package god-mode
    :ensure t
    :bind
    (("<f8>" . 'god-mode-all)
     ("<right>" . 'god-mode-all)
     :map god-local-mode-map
     ("." . 'repeat))
    :init
    (require 'my-mode-line)
    (add-hook 'god-mode-enabled-hook 'mode-line-purple)
    (add-hook 'god-mode-disabled-hook 'mode-line-green)
    :config
    (setq god-exempt-major-modes nil
          god-exempt-predicates nil)
    (god-mode))
#+END_SRC

*** Quality of life

**** Smex

smex integrates "M-x" with =ido=
#+BEGIN_SRC emacs-lisp
  (use-package smex
    :ensure t
    :init (smex-initialize)
    :bind
    ("M-x" . smex))
#+END_SRC

**** Which-key

Shows what your keys do
# #+BEGIN_SRC emacs-lisp
#   (use-package which-key
#     :ensure t
#     :init (which-key-mode)
#     :config (which-key-enable-god-mode-support))
# #+END_SRC

**** Try

Allows you to try other packages without committing
#+BEGIN_SRC emacs-lisp
  (use-package try
    :ensure t)
#+END_SRC

*** Not really useful

**** Lorem Ipsum

A 'Lorem ipsum' generator
#+BEGIN_SRC emacs-lisp
  (use-package lorem-ipsum
    :ensure t)
#+END_SRC

*** To be confirmed

**** Elpher - gopher client

#+BEGIN_SRC emacs-lisp
  (use-package elpher
    :ensure t)
#+END_SRC

**** xclip - enable use of X11 clipboard in terminal

#+BEGIN_SRC emacs-lisp
  (use-package xclip
    :ensure t)
#+END_SRC

*** PDF-tools

Majorly increases performance when viewing pdfs as a file
#+BEGIN_SRC emacs-lisp
  (use-package pdf-tools
    :ensure t)
#+END_SRC

*** Mine

**** Toggle-touchpad

A simple package I wrote to toggle the touchpad/trackpoint on my
ThinkPad

#+BEGIN_SRC emacs-lisp
  (use-package toggle-touchpad
    :load-path "~/.emacs.d/lisp/"
    :after init
    :bind
    (("<XF86TouchpadToggle>" . 'toggle-touchpad)
     ("C-z \\" . 'toggle-touchpad)))
#+END_SRC

* Stuff to do when loading

** Environment Variables

Setting path, email and password variables
#+BEGIN_SRC emacs-lisp
  ;  (setenv "NOTMUCH_CONFIG"
  ;          (expand-file-name "~/.config/notmuch-config"))
  ;  (setenv "PASSWORD_STORE_DIR"
  ;          (expand-file-name "~/.local/share/password-store/"))
#+END_SRC

* Fixing defaults

** Miscellaneous

*** Swap yes/no prompt with y/n

#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

*** Enable all the features

#+BEGIN_SRC emacs-lisp
  (setq disabled-command-function nil)
#+END_SRC

** Aesthetics

*** Colours

#+BEGIN_SRC emacs-lisp
  (set-background-color "#ffffd0")
  (set-cursor-color "red")
#+END_SRC

*** GUI ugliness

Disable all the wasteful bars
#+BEGIN_SRC emacs-lisp
  (when (window-system)
    (scroll-bar-mode -1)
    (fringe-mode 1))
  (menu-bar-mode -1)
  (tool-bar-mode -1)

#+END_SRC

*** Fonts

This section has been moved to a different file: =./config/fonts.el=
#+BEGIN_SRC emacs-lisp
;  (load-file (concat default-directory config/fonts.el))
#+END_SRC

*** Disable audible and visual bell

#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC

*** Form-feed (^L  )

#+BEGIN_SRC emacs-lisp
                                          ;  (show-formfeed-as-pilcrow)
#+END_SRC

** Tabs

Tabs are 4 spaces wide
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq tab-width 4)
#+END_SRC

** Buffers/input

*** ido-mode

ido-mode is much better than the default for switching
buffers and going to files.
#+BEGIN_SRC emacs-lisp
  (setq ido-enable-flex-matching nil)
  (setq ido-create-new-buffer 'always)
  (setq ido-everywhere t)
  (ido-mode 1)
#+END_SRC

*** ibuffer

ibuffer is also a lot better than the default
(plus it has colours)
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC

** desktop-save

#+BEGIN_SRC emacs-lisp
  (desktop-save-mode t)
#+END_SRC

** Help

Use a keybinding for viewing manpages

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-h C-m") 'man)
#+END_SRC

* Custom functions

** Resizing windows

#+BEGIN_SRC emacs-lisp
  (defun v-resize (key)
    "interactively resize the window"  
    (interactive "cHit p/n/b/f to resize") 
    (cond                                  
     ((eq key (string-to-char "n"))                      
      (enlarge-window 1)             
      (call-interactively 'v-resize)) 
     ((eq key (string-to-char "p"))                      
      (enlarge-window -1)             
      (call-interactively 'v-resize)) 
     ((eq key (string-to-char "b"))                      
      (enlarge-window-horizontally -1)             
      (call-interactively 'v-resize)) 
     ((eq key (string-to-char "f"))                      
      (enlarge-window-horizontally 1)            
      (call-interactively 'v-resize)) 
     (t (push key unread-command-events))))
  (global-set-key (kbd "C-c +") 'v-resize)
#+END_SRC

** Go to config file

Visit your config file. Bound to "C-c e" in =Keybindings= section.
#+BEGIN_SRC emacs-lisp
  (defun config-visit ()
    "Go to your config.org"
    (interactive)
    (find-file "~/.emacs.d/config.org"))
#+END_SRC

** Ido

*** Bookmarks

#+BEGIN_SRC emacs-lisp
  (defun ido-bookmark-jump ()
    "An ido wrapper for `bookmark-jump'. Designed for interactive
  use, so just use `bookmark-jump' in elisp."
    (interactive)
    (bookmark-maybe-load-default-file)
    (bookmark-jump
     (ido-completing-read "Bookmark: " bookmark-alist)))
#+END_SRC

** Reloading config

Reloads this config file. Bound to "C-c r" in Keybindings section.
#+BEGIN_SRC emacs-lisp
  (defun config-reload ()
    "Reloads ~/.emacs.d/config.org at runtime"
    (interactive)
    (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
#+END_SRC

** Programming

*** Opening Output

#+BEGIN_SRC emacs-lisp
  (defun opout ()
    "Opens a pdf file of the same name as the current file"
    (interactive)
    (find-file-other-window (concat
                             (file-name-sans-extension buffer-file-name)
                             ".pdf")))
#+END_SRC

** Email

#+BEGIN_SRC emacs-lisp
  (defun mailsync ()
    "Downloads new mail and adds it to the notmuch database"
    (interactive)
    (shell-command "mbsync -a && notmuch new &" "*mailsync*"))
#+END_SRC

** WM stuff

*** Notification bar replacement

#+BEGIN_SRC emacs-lisp
  (defun notibar ()
    "Brings up a notification with the following information:
  Date
  Time
  Memory used
  Disk available
  Brightness level
  Volume level
  Battery level"
    (interactive)
    (call-process "notibar"))
#+END_SRC

*** dmenu

**** dmenu launcher

#+BEGIN_SRC emacs-lisp
  (defun dmenu_recency ()
    "Launch a program with dmenu"
    (interactive)
    (start-process "dmenu_recency" nil
                   "dmenu_recency"))
#+END_SRC

**** dmenuhandler

#+BEGIN_SRC emacs-lisp
  (defun dmenuhandler ()
    "Choose how to handle the url in X11 clipboard"
    (interactive)
    (shell-command (concat "dmenuhandler " (car kill-ring) " &")))
#+END_SRC

**** pdf-opener

This used to just call an external shell script, but I replaced it
with a more emacsy version.

#+BEGIN_SRC emacs-lisp
  (defun list-documents (&optional dir)
    "Using `find-dired', list all the postscript and pdf files a
  specified directory.  If called interactively, prompt for
  Directory. Else, DIR will default to ~/Documents/."
    (interactive (list (read-directory-name "Find videos where: " "~/Documents/")))
    (unless dir
      (setq dir "~/Documents/"))
    (find-dired dir
                "\\( -iname \\*.ps -o -iname \\*.pdf \\)")
    (dired-hide-details-mode t)
    (setq truncate-lines t))
#+END_SRC

**** video-opener

This used to just call an external shell script, but I replaced it
with a more emacsy version. In order to open videos externally,
=openwith= must be installed as above.

#+BEGIN_SRC emacs-lisp
(defun list-videos (&optional dir)
  "Using `find-dired', list all the videos a specified directory.
If called interactively, prompt for Directory. Else, DIR will
default to ~/Downloads/."
  (interactive (list (read-directory-name "Find videos where: " "~/Downloads/")))
  (unless dir
    (setq dir "~/Downloads/"))
  (find-dired dir
              "\\( -iname \\*.mkv -o -iname \\*.avi -o -iname \\*.mp4 -o -iname \\*.webm \\)")
  (dired-hide-details-mode t)
  (setq truncate-lines t))
#+END_SRC

** Other
*** Xah Lee form feed

#+BEGIN_SRC emacs-lisp
  (defun show-formfeed-as-pilcrow ()
    "Display the formfeed ^L char as pilcrow (¶)."
    (interactive)
    (progn
      (when (not buffer-display-table)
        (setq buffer-display-table (make-display-table)))
      (aset buffer-display-table ?\^L
            (vconcat (make-list 1 (make-glyph-code ?¶ 'font-lock-comment-face))))
      (redraw-frame)))
#+END_SRC

** Fixing packages

#+BEGIN_SRC emacs-lisp

  (defun transmission ()
    "Open a `transmission-mode' buffer."
    (interactive)
    (let* ((name "*transmission*")
           (buffer (or (get-buffer name)
                       (generate-new-buffer name))))
      (transmission-turtle-poll)
      (unless (eq buffer (current-buffer))
        (with-current-buffer buffer
          (unless (eq major-mode 'transmission-mode)
            (condition-case e
                (progn
                  (transmission-mode)
                  (transmission-draw)
                  (goto-char (point-min)))
              (error
               (kill-buffer buffer)
               (signal (car e) (cdr e))))))
        (switch-to-buffer buffer))))
#+END_SRC

* Major mode hooks and variables

** Lilypond mode

Use lilypond mode for .ly files
(taken from lilypond.org)
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "/usr/share/emacs/site-lisp")
  (require 'lilypond-mode)
  (add-to-list 'load-path "~/.emacs.d/lisp/sane-lilypond")
  (require 'sane-lilypond-mode)
  (add-hook 'LilyPond-mode-hook
            (lambda () (interactive)
              (local-set-key (kbd "C-i") 'sane-lilypond-indent)
              (local-set-key (kbd "<S-iso-lefttab>") 'sane-lilypond-deindent)))
#+END_SRC

** Electric pairs

Auto-add parentheses
#+BEGIN_SRC emacs-lisp
  (setq electric-pair-pairs '(
                              (?\( . ?\))
                              ))
#+END_SRC
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook (electric-pair-mode t))
#+END_SRC

** Org Mode

#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (setq org-src-window-setup 'current-window)
  (setq org-src-tab-acts-natively t)
  (setq org-ellipsis nil)
#+END_SRC

** M-x compile hooks

*** Groff

#+BEGIN_SRC emacs-lisp
  (add-hook 'nroff-mode-hook
            (lambda ()
              (set (make-local-variable 'compile-command)
                   (format "groff -ms -Tpdf %s > %s" 
                           (shell-quote-argument buffer-file-name)
                           (concat (file-name-sans-extension
                                    (shell-quote-argument
                                     buffer-file-name)) ".pdf")))))


#+END_SRC

*** C

#+BEGIN_SRC emacs-lisp
  (add-hook 'c-mode-hook
            (lambda ()
              (set (make-local-variable 'compile-command)
                   (format "compiler %s" buffer-file-name))))
#+END_SRC

*** LilyPond

#+BEGIN_SRC emacs-lisp
  (add-hook 'LilyPond-mode-hook
            (lambda ()
              (set (make-local-variable 'compile-command)
                   (format "lilypond %s" buffer-file-name))))
#+END_SRC

*** LaTeX

#+BEGIN_SRC emacs-lisp
  (add-hook 'latex-mode-hook
            (lambda ()
              (set (make-local-variable 'compile-command)
                   (format "pdflatex %s" buffer-file-name))))
#+END_SRC

Somewhat related, overrides latex-mode keybinding that interferes with
my compile key "C-c C-m".
#+BEGIN_SRC emacs-lisp
  (add-hook 'latex-mode-hook
            (lambda ()
              (local-unset-key (kbd "C-c C-m"))))
#+END_SRC

** Info-mode

#+BEGIN_SRC emacs-lisp
  (add-hook 'Info-mode-hook 'variable-pitch-mode)
#+END_SRC

* Keybindings

** Alias <menu> to C-x

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<menu>") ctl-x-map)
#+END_SRC

** Remove =C-z=

#+BEGIN_SRC emacs-lisp
  (global-unset-key (kbd "C-z"))
#+END_SRC
** Interaction with Emacs

*** ido-bookmark-jump (custom function)

Open a bookmark with the default keybinding =C-x r b=, but with ido

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x r b") 'ido-bookmark-jump)
#+END_SRC

*** eww-list-bookmarks
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x r e") 'eww-list-bookmarks)
#+END_SRC
*** Terminal functionality

Rebinding some useful keys that can't be used in a terminal.

#+BEGIN_SRC emacs-lisp
  (unless (window-system)
    ;; Comments -- C-x C-;
    (global-set-key (kbd "C-c ;") 'comment-line)
    ;; Indentation -- C-M-\"
    (global-set-key (kbd "C-c \\") 'indent-region))
#+END_SRC

*** bury-buffer and kill-buffer-and-window

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-z C-z") 'bury-buffer)
  (global-set-key (kbd "C-z z") 'kill-buffer-and-window)
#+END_SRC
** Config

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c r") 'config-reload)
#+END_SRC

** General WM stuff

*** System information

Built-in battery function with =C-z b=.
Custom notification script with =C-z C-b=. 

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-z b") 'battery)
  (global-set-key (kbd "C-z C-b") 'notibar)
#+END_SRC

*** dmenu scripts

I still have some use for dmenu, despite only using emacs...
All commands are prefixed with =C-z=
| d | enter commands into dmenu       |
| p | select a pdf to open with emacs |
| v | select a video to open with mpv |
| D | choose what to do with a URL    |

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-z d") 'dmenu_recency)
  (global-set-key (kbd "C-z p") 'list-documents)
  (global-set-key (kbd "C-z v") 'list-videos)
  (global-set-key (kbd "C-z D") 'dmenuhandler)
#+END_SRC

** Programming/Typesetting

Bind emacs compile to =C-c C-m=. This allows 2 rapid presses of =C-m=
or =RET= to skip the prompt.

"opout" is a script to open the output of a file (e.g. TeX,
LilyPond).

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c C-m") 'compile)
  (global-set-key (kbd "C-c p") 'opout)
#+END_SRC

** Miscellaneous

*** Line numbers

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c n") 'display-line-numbers-mode)
#+END_SRC

*** Spelling correction

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c s") 'flyspell-mode)
#+END_SRC

*** Line wrap

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c l") 'toggle-truncate-lines)
#+END_SRC

* Mode-line

Just some basic extra stuff in the mode-line.
I don't want anything fancy.
#+BEGIN_SRC emacs-lisp
  (column-number-mode t)
  (display-time-mode t)
  (setq display-time-24hr-format 1)
#+END_SRC

* Email

email settings
#+BEGIN_SRC emacs-lisp
  (setq send-mail-function 'sendmail-send-it
        sendmail-program "/usr/bin/msmtp"
        mail-specify-envelope-from t
        message-sendmail-envelope-from 'header
        mail-envelope-from 'header)
#+END_SRC












